package entities;
// Generated Oct 9, 2015 3:18:50 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtdatphongId generated by hbm2java
 */
@Embeddable
public class CtdatphongId implements java.io.Serializable {

	private int idkhach;
	private int idphong;

	public CtdatphongId() {
	}

	public CtdatphongId(int idkhach, int idphong) {
		this.idkhach = idkhach;
		this.idphong = idphong;
	}

	@Column(name = "IDKhach", nullable = false)
	public int getIdkhach() {
		return this.idkhach;
	}

	public void setIdkhach(int idkhach) {
		this.idkhach = idkhach;
	}

	@Column(name = "IDPhong", nullable = false)
	public int getIdphong() {
		return this.idphong;
	}

	public void setIdphong(int idphong) {
		this.idphong = idphong;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtdatphongId))
			return false;
		CtdatphongId castOther = (CtdatphongId) other;

		return (this.getIdkhach() == castOther.getIdkhach()) && (this.getIdphong() == castOther.getIdphong());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdkhach();
		result = 37 * result + this.getIdphong();
		return result;
	}

}
